pref("extensions.pyha32.spams", 1);
pref("extensions.pyha32.themes", 1);
pref("extensions.pyha32.skin", 2);
pref("extensions.pyha32.mesto", "status-bar");
pref("extensions.pyha32.raspalaga", 1);
pref("extensions.pyha32.gourl", 0);
pref("extensions.pyha32.page", 1);
pref("extensions.pyha32.time", 1);
pref("extensions.pyha32.onoff", 1);